from pathlib import Path
p=Path('/mnt/data/cmj-v414-work/src/dashboard/dashboard.js')
s=p.read_text()
start=s.index('function card(x,p){')
end=s.index('function renderOverview(){', start)
new=r'''function difficultyFor(level){return ({A1:'Beginner',A2:'Beginner',B1:'Intermediate',B2:'Intermediate',C1:'Advanced',C2:'Advanced'})[String(level||'').toUpperCase()]||'Beginner'}
function languageName(code){return ({tr:'Turkish',en:'English',ur:'Urdu',ar:'Arabic',fa:'Persian',de:'German',fr:'French',es:'Spanish',it:'Italian',pt:'Portuguese',ru:'Russian'}[String(code||'').toLowerCase()]||code||'Language')}
function itemTitle(x){return x.videoTitle||x.title||x.word||x.sentence||x.label||'Learning item'}
function itemTimestamp(x){return x.timestamp!=null?Number(x.timestamp):x.lastPosition!=null?Number(x.lastPosition):0}
function isSentenceItem(x){return x.type==='sentence'||Boolean(x.sentence&&(!x.word||x.sentence!==x.word))}
function card(x,p){
 let isVideo=['history','continue','videos'].includes(p.id),title=itemTitle(x),sub=x.word?`${x.word}${x.translation?' — '+x.translation:''}`:x.sentence||x.subtitle||x.label||'',time=itemTimestamp(x),thumb=x.thumbnail||(x.videoId?`https://i.ytimg.com/vi/${encodeURIComponent(x.videoId)}/hqdefault.jpg`:''),progress=Number(x.watchPercentage??x.progress??0),url=x.url?ts(x.url,time):'';
 let itemId=x.id||x.videoId||'';
 let actions=`<button data-details-item="${esc(itemId)}">▣ Details / Card</button><button data-copy-item="${esc(itemId)}">📋 Copy</button>`;
 if(p.key)actions+=`<button data-add-custom="${esc(itemId)}" data-source="${esc(p.key)}" data-collection-mode="copy">＋ Add to Collection</button>`;
 if(p.custom)actions+=`<button data-add-custom="${esc(itemId)}" data-source="${esc(p.key)}" data-collection-mode="move">↔ Move to Collection</button>`;
 if(x.videoId)actions+=`<button data-checkpoint="${esc(x.videoId)}" data-time="${esc(time)}">📍 Checkpoint</button>`;
 if(x.url)actions+=`<button data-favorite="${esc(x.videoId||x.id||'')}">⭐ Favorite</button>`;
 if(isVideo&&x.url)actions+=`<button data-resume="${esc(x.videoId)}">▶ Resume</button>`;
 if(x.url)actions+=`<button data-open="${esc(url)}">Open at ${esc(fmt(time))}</button>`;
 actions+=`<button data-download-item="${esc(itemId)}">⬇ Download</button><button data-export-item="${esc(itemId)}">⇩ Export</button>`;
 if(p.key)actions+=`<button data-remove-item="${esc(x.id||'')}">🗑 Remove</button>`;
 return `<article class="item-card ${x.status==='completed'?'completed':''}">
 ${thumb?`<img class="thumb" src="${esc(thumb)}" alt="" loading="lazy">`:''}<div class="item-body"><div class="card-top"><span class="pill">${esc(p.name)}</span>${x.status?`<span class="status ${esc(x.status)}">${esc(x.status)}</span>`:''}</div>
 <h3 class="item-title">${url?`<a href="${esc(url)}" target="_blank" rel="noopener">${esc(title)}</a>`:esc(title)}</h3><p class="item-meta"><strong>${esc(sub)}</strong></p>
 ${isVideo?`<div class="progress"><span style="width:${Math.max(0,Math.min(100,progress))}%"></span></div><p class="item-context">${Math.round(progress)}% · Last ${esc(time?fmt(time):'00:00:00')} · Sessions ${esc(x.sessions||1)}</p>`:''}
 <p class="item-context">${esc(x.source||'Library')}${time?` · ${esc(fmt(time))}`:''}${x.pos?` · ${esc(x.pos)}`:''}${x.level?` · ${esc(x.level)}`:''}${x.level?` · ${esc(difficultyFor(x.level))}`:''}</p>${x.sentence&&x.word?`<p class="item-context">${esc(x.sentence)}</p>`:''}${x.note?`<p class="note-preview">${esc(x.note)}</p>`:''}<div class="tags">${(x.tags||[]).map(t=>`<span>#${esc(t)}</span>`).join('')}</div><div class="item-actions">${actions}</div></div></article>`;
}
'''
s=s[:start]+new+s[end:]
# replace onClick with expanded handlers
old=""" let ci=e.target.closest('[data-copy-item]');if(ci){copyItem(ci.dataset.copyItem);return}
 if(e.target.matches('[data-close]'))e.target.closest('dialog')?.close();
}"""
new2=""" let ci=e.target.closest('[data-copy-item]');if(ci){copyItem(ci.dataset.copyItem);return}
 let de=e.target.closest('[data-details-item]');if(de){showDetails(de.dataset.detailsItem);return}
 let di=e.target.closest('[data-download-item]');if(di){downloadSingleItem(di.dataset.downloadItem);return}
 let ei=e.target.closest('[data-export-item]');if(ei){openItemExport(ei.dataset.exportItem);return}
 if(e.target.matches('[data-close]'))e.target.closest('dialog')?.close();
}"""
if old not in s: raise SystemExit('onclick marker missing')
s=s.replace(old,new2)
# replace export block
start=s.index('async function copyItem(id){')
end=s.index('async function importPage(e){', start)
new3=r'''async function copyItem(id){let x=data.find(a=>(a.id||a.videoId)===id);if(!x)return;navigator.clipboard.writeText(readable([x],info()));notify('Item copied.');}
async function copyPage(){await navigator.clipboard.writeText(readable(data,info()));notify(`Copied ${data.length} item(s) from ${info().name}.`)}
let exportSingleItem=null,exportSinglePage=null;
async function openExport(downloadOnly){exportSingleItem=null;exportSinglePage=null;let choices=allPages().map(p=>`<label class="choice"><input type="checkbox" value="${esc(p.id)}" ${p.id===current?'checked':''}>${p.icon} ${esc(p.name)}</label>`).join('');$('#exportChoices').innerHTML=choices;$('#exportTitle').textContent=downloadOnly?'Download selected library':'Export selected library';$('#exportDescription').textContent='Select one or more Library sections, then choose the output format.';$('#exportFormat').disabled=false;$('#exportFormat').value='txt';$('#exportDialog').showModal()}
async function openItemExport(id){let x=data.find(a=>(a.id||a.videoId)===id);if(!x)return;exportSingleItem=x;exportSinglePage=info();$('#exportChoices').innerHTML=`<label class="choice"><input type="checkbox" checked disabled> ${esc(exportSinglePage.icon||'📚')} ${esc(exportSinglePage.name)} — selected item only</label>`;$('#exportTitle').textContent='Export this Library item';$('#exportDescription').textContent='The selected word, sentence, or learning item will be exported with its learning details.';$('#exportFormat').disabled=false;$('#exportFormat').value='txt';$('#exportDialog').showModal()}
async function downloadSingleItem(id){await openItemExport(id)}
async function submitExport(e){e.preventDefault();let bundles=[];if(exportSingleItem&&exportSinglePage){bundles=[{page:exportSinglePage,items:[exportSingleItem]}]}else{let ids=[...$('#exportChoices input:checked')].map(x=>x.value);if(!ids.length)return notify('Select at least one page.');for(let id of ids){let p=infoBy(id);bundles.push({page:p,items:await pageData(p)})}}
 let fmtType=$('#exportFormat').value,payload=JSON.stringify({program:'Charlie MJ Language',version:'4.1.4',exportedAt:new Date().toISOString(),pages:bundles},null,2),mime='application/json',ext='json';
 if(fmtType==='txt'){payload=bundles.map(b=>readable(b.items,b.page)).join('\n\n'+'='.repeat(80)+'\n\n');mime='text/plain';ext='txt'}
 if(fmtType==='md'){payload=bundles.map(b=>markdown(b.items,b.page)).join('\n\n---\n\n');mime='text/markdown';ext='md'}
 if(fmtType==='doc'){payload=bundles.map(b=>docHtml(b.items,b.page)).join('<hr>');payload=docDocument(payload);mime='application/msword';ext='doc'}
 if(fmtType==='pdf'){let text=bundles.map(b=>readable(b.items,b.page)).join('\n\n'+'='.repeat(80)+'\n\n');let pdf=await pdfFromText(text);let set=(await chrome.storage.local.get('settings')).settings||{};await downloadBinary(`${set.downloadRoot||'Charlie MJ Language'}/Exports/${safe(bundles.map(x=>x.page.name).join('-'))}.pdf`,pdf,'application/pdf');$('#exportDialog').close();notify('PDF export started.');exportSingleItem=null;return}
 if(fmtType==='csv'){payload=csv(bundles.flatMap(b=>b.items.map(x=>({page:b.page.name,...x}))));mime='text/csv';ext='csv'}
 if(fmtType==='anki'){payload=bundles.flatMap(b=>b.items).map(x=>`${String(x.word||x.sentence||'').replaceAll('\\t',' ')}\\t${String(x.translation||x.sentenceTranslation||'').replaceAll('\\t',' ')}\\t${String(x.sentence||'').replaceAll('\\t',' ')}`).join('\\n');mime='text/tab-separated-values';ext='txt'}
 if(['srt','vtt'].includes(fmtType)){let rows=bundles.flatMap(b=>b.items).filter(x=>x.sentence||x.subtitle).map((x,i)=>`${fmtType==='srt'?i+1+'\\n':''}${timecode(x.timestamp||0,fmtType)} --> ${timecode((x.timestamp||0)+(x.duration||2),fmtType)}\\n${x.sentence||x.subtitle||''}${x.translation||x.sentenceTranslation?'\\n'+(x.translation||x.sentenceTranslation):''}`).join('\\n\\n');payload=fmtType==='vtt'?'WEBVTT\\n\\n'+rows:rows;mime='text/plain';ext=fmtType}
 let set=(await chrome.storage.local.get('settings')).settings||{};await download(`${set.downloadRoot||'Charlie MJ Language'}/Exports/${safe(bundles.map(x=>x.page.name).join('-'))}.${ext}`,payload,mime);$('#exportDialog').close();notify(`${fmtType.toUpperCase()} export started.`);exportSingleItem=null;exportSinglePage=null}
function markdown(items,p){let out=[`# Charlie MJ Language — ${p.name}`,``,`Exported: ${new Date().toLocaleString()}`,``,`Total items: ${items.length}`,``];items.forEach((x,i)=>{out.push(`## ${i+1}. ${itemTitle(x)}`);if(x.word)out.push(`- **Word:** ${x.word}`);if(x.sentence)out.push(`- **Sentence:** ${x.sentence}`);out.push(`- **Translation:** ${x.translation||x.sentenceTranslation||''}`,`- **Language:** ${languageName(x.language)}`,`- **Level:** ${x.level||'A1'} — ${difficultyFor(x.level)}`,`- **Video:** ${x.videoTitle||x.title||''}`,`- **URL:** ${x.url||''}`,`- **Timestamp:** ${fmt(itemTimestamp(x))}`,`- **Saved:** ${x.createdAt||x.learnedAt||''}`);if(x.pos)out.push(`- **Part of speech:** ${x.pos}`);if(x.lemma)out.push(`- **Lemma:** ${x.lemma}`);if(x.tags?.length)out.push(`- **Tags:** ${x.tags.join(', ')}`);if(x.note)out.push(`- **Notes:** ${x.note}`);if(isSentenceItem(x))out.push('',sentenceMarkdown(x));out.push('')});return out.join('\n')}
function sentenceMarkdown(x){let words=Array.isArray(x.words)&&x.words.length?x.words:deriveSentenceWords(x);let lines=['### Sentence Study','',`**Complete translation:** ${x.sentenceTranslation||x.translation||''}`,'','| Original | Meaning | POS | Lemma | Suffix / Grammar |','|---|---|---|---|---|'];for(const w of words)lines.push(`| ${w.word||''} | ${w.translation||'—'} | ${w.posLabel||w.pos||'Other'} | ${w.lemma||'—'} | ${w.suffix||w.morphologyLabel||'—'} |`);return lines.join('\n')}
function docDocument(body){return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>body{font-family:Arial,sans-serif;line-height:1.5;color:#111}h1{font-size:24pt}h2{font-size:16pt;margin-top:24pt}h3{font-size:13pt}table{border-collapse:collapse;width:100%}td,th{border:1px solid #999;padding:6px;text-align:left}.meta{color:#555}</style></head><body>${body}</body></html>`}
function docHtml(items,p){return `<h1>Charlie MJ Language — ${esc(p.name)}</h1><p class="meta">Exported ${esc(new Date().toLocaleString())} · ${items.length} item(s)</p>${items.map((x,i)=>`<h2>${i+1}. ${esc(itemTitle(x))}</h2><p><strong>Original:</strong> ${esc(x.word||x.sentence||x.title||'')}</p><p><strong>Translation:</strong> ${esc(x.translation||x.sentenceTranslation||'')}</p><p><strong>Language:</strong> ${esc(languageName(x.language))} · <strong>Level:</strong> ${esc(x.level||'A1')} · <strong>Difficulty:</strong> ${esc(difficultyFor(x.level))}</p><p><strong>Video:</strong> ${esc(x.videoTitle||x.title||'')}<br><strong>URL:</strong> ${esc(x.url||'')}<br><strong>Timestamp:</strong> ${esc(fmt(itemTimestamp(x)))}<br><strong>Saved:</strong> ${esc(x.createdAt||x.learnedAt||'')}</p>${x.pos?`<p><strong>POS:</strong> ${esc(x.pos)}</p>`:''}${x.lemma?`<p><strong>Lemma:</strong> ${esc(x.lemma)}</p>`:''}${x.tags?.length?`<p><strong>Tags:</strong> ${esc(x.tags.join(', '))}</p>`:''}${x.note?`<p><strong>Notes:</strong> ${esc(x.note)}</p>`:''}${isSentenceItem(x)?docSentence(x):''}`).join('')}`}
function docSentence(x){let words=Array.isArray(x.words)&&x.words.length?x.words:deriveSentenceWords(x);return `<h3>Sentence Study</h3><p><strong>Complete translation:</strong> ${esc(x.sentenceTranslation||x.translation||'')}</p><table><thead><tr><th>Original</th><th>Meaning</th><th>POS</th><th>Lemma</th><th>Suffix / Grammar</th></tr></thead><tbody>${words.map(w=>`<tr><td>${esc(w.word||'')}</td><td>${esc(w.translation||'—')}</td><td>${esc(w.posLabel||w.pos||'Other')}</td><td>${esc(w.lemma||'—')}</td><td>${esc(w.suffix||w.morphologyLabel||'—')}</td></tr>`).join('')}</tbody></table>`}
function deriveSentenceWords(x){return String(x.sentence||'').split(/\s+/).filter(Boolean).map(word=>analyzeStoredWord(word,x))}
function analyzeStoredWord(raw,x){let word=String(raw||'').replace(/^[\s.,!?;:"“”‘’]+|[\s.,!?;:"“”‘’]+$/g,''),lower=word.toLocaleLowerCase('tr');let pronouns=new Set(['ben','sen','o','biz','siz','onlar','bana','sana','ona','bizi','sizi','onları','benim','senin','onun','bizim','sizin','onların']);let verb=/(iyor|ıyor|uyor|üyor|acak|ecek|miş|mış|muş|müş|di|dı|du|dü|mak|mek|yor)(um|ım|im|üm|sun|sın|sin|sunuz|siniz|sünüz|ız|iz|uz|üz)?$/i.test(lower);let pos=pronouns.has(lower)?'Pronoun':verb?'Verb':'Noun';let lemma=verb?lower.replace(/(iyor|ıyor|uyor|üyor)(um|ım|im|üm|sun|sın|sin|sunuz|siniz|sünüz|ız|iz|uz|üz)?$/i,'').replace(/(acak|ecek|miş|mış|muş|müş|di|dı|du|dü)(m|n|k)?$/i,'')+'mek':lower;let suffixMatch=lower.match(/(ımız|imiz|umuz|ümüz|ınız|iniz|unuz|ünüz|lar|ler|iyor|ıyor|uyor|üyor|acak|ecek|miş|mış|muş|müş|lik|lık|luk|lük|siz|sız|suz|süz|ci|cı|cu|cü|li|lı|lu|lü|den|dan|de|da|i|ı|u|ü)$/i);let suffix=suffixMatch?suffixMatch[0]:'';let label=suffix?(/(den|dan|de|da)$/i.test(suffix)?'Case suffix':/(lar|ler)$/i.test(suffix)?'Plural suffix':/(iyor|ıyor|uyor|üyor|acak|ecek|miş|mış|muş|müş)$/i.test(suffix)?'Tense / aspect suffix':'Turkish suffix'):'';return {word,pos,posLabel:pos,lemma,suffix,morphologyLabel:label,translation:x?.words?.find(w=>String(w.word||'').toLowerCase()===lower)?.translation||''}}
async function showDetails(id){let x=data.find(a=>(a.id||a.videoId)===id);if(!x)return;let favs=(await chrome.storage.local.get('favorites')).favorites||[],isFav=favs.some(f=>(f.videoId&&x.videoId&&f.videoId===x.videoId)||(f.id&&x.id&&f.id===x.id));let collectionNames=[];for(const p of pages){let a=await loadSource(`libraryPage_${p.id}`);if(a.some(y=>(y.id&&x.id&&y.id===x.id)||(!x.id&&y.videoId===x.videoId&&y.type===x.type)))collectionNames.push(p.name)}$('#detailsTitle').textContent=isSentenceItem(x)?'Sentence Learning Card':'Vocabulary / Learning Card';$('#detailsBody').innerHTML=detailsHtml(x,isFav,collectionNames);$('#detailsDialog').showModal();if(isSentenceItem(x))enhanceSentenceDetails(x)}
function detailsHtml(x,isFav,collections){let level=x.level||'A1',diff=x.difficulty||difficultyFor(level),saved=x.createdAt||x.learnedAt||x.savedAt||'',time=itemTimestamp(x),url=x.url?ts(x.url,time):'';let rows=[['Original',x.word||x.sentence||x.title||''],['Translation',x.translation||x.sentenceTranslation||''],['Language',languageName(x.language)],['Language level',`${level} — ${diff}`],['Video title',x.videoTitle||x.title||''],['Video URL',x.url||''],['Timestamp',fmt(time)],['Date saved / learned',saved?new Date(saved).toLocaleString():'—'],['Collection',collections.length?collections.join(', '):'Not added'],['Favorite',isFav?'Yes':'No'],['Tags / labels',(x.tags||[]).join(', ')||'—'],['Notes',x.note||x.notes||'—'],['Source / context',x.source||'Library'],['POS',x.pos||'—'],['Lemma / base form',x.lemma||'—']];return `<div class="details-hero"><div class="details-original">${esc(x.word||x.sentence||x.title||'Learning item')}</div><div class="details-translation">${esc(x.translation||x.sentenceTranslation||'Translation not saved')}</div>${url?`<button class="primary" data-details-open="${esc(url)}">▶ Open YouTube at ${esc(fmt(time))}</button>`:''}</div><div class="details-grid">${rows.map(r=>`<div class="detail-row"><span>${esc(r[0])}</span><strong>${esc(r[1])}</strong></div>`).join('')}</div>${isSentenceItem(x)?`<section class="sentence-study"><h3>Sentence Grammar & Word Study</h3><p class="study-translation"><strong>Complete sentence translation:</strong> ${esc(x.sentenceTranslation||x.translation||'')}</p><div id="sentenceAnalysisBody"><p>Preparing word-by-word analysis…</p></div></section>`:''}`}
async function enhanceSentenceDetails(x){let words=Array.isArray(x.words)&&x.words.length?x.words.map(w=>({...w,word:w.word||''})):deriveSentenceWords(x);if(!words.length)return;let missing=words.filter(w=>!w.translation);if(missing.length){let settings=(await chrome.storage.local.get('settings')).settings||{};let source=settings.sourceLanguage||'tr',target=settings.targetLanguage||'en';let results=await Promise.all(words.map(async w=>{if(w.translation)return w;try{let r=await fetch(`https://api.mymemory.translated.net/get?q=${encodeURIComponent(w.word)}&langpair=${encodeURIComponent(source+'|'+target)}`);let j=await r.json();return {...w,translation:j?.responseData?.translatedText||''}}catch{return w}}));words=results;let updated={...x,words};await persistWords(updated)}let el=$('#sentenceAnalysisBody');if(el)el.innerHTML=`<div class="word-study-grid">${words.map(w=>`<article class="word-study ${esc(String(w.pos||w.posLabel||'other').toLowerCase())}" style="--word-role:${esc(w.color||roleColor(w.pos||w.posLabel))}"><div class="study-word">${esc(w.word)}</div><div class="study-meaning">${esc(w.translation||'—')}</div><div class="study-meta"><span>${esc(w.posLabel||w.pos||'Other')}</span><span>${esc(w.cefr||x.level||'A1')}</span></div><div class="study-lemma">Base / lemma: <strong>${esc(w.lemma||analyzeStoredWord(w.word,x).lemma||'—')}</strong></div>${w.suffix||w.morphologyLabel?`<div class="study-suffix">${esc(w.suffix||'')} ${esc(w.morphologyLabel||'Turkish suffix')}</div>`:''}</article>`).join('')}</div>`}
async function persistWords(updated){for(const key of ['vocabulary','sentenceLearning']){let s=await chrome.storage.local.get(key),a=Array.isArray(s[key])?s[key]:[],i=a.findIndex(y=>y.id===updated.id);if(i>=0)a[i]=updated;await chrome.storage.local.set({[key]:a})}}
function roleColor(pos){return ({noun:'#38bdf8',verb:'#fb7185',adjective:'#a78bfa',adverb:'#4ade80',pronoun:'#facc15',preposition:'#f472b6',conjunction:'#fb923c',determiner:'#818cf8',numeral:'#a3e635',particle:'#22d3ee'}[String(pos||'').toLowerCase()]||'#e2e8f0')}
function readable(items,p){let l=[`Charlie MJ Language`,`Library: ${p.name}`,`Exported: ${new Date().toLocaleString()}`,`Total items: ${items.length}`,''];items.forEach((x,i)=>{l.push(`• ${itemTitle(x)}`);if(x.word)l.push(`  Word: ${x.word}`);if(x.sentence)l.push(`  Sentence: ${x.sentence}`);l.push(`  Translation: ${x.translation||x.sentenceTranslation||''}`,`  Language: ${languageName(x.language)}`,`  Level: ${x.level||'A1'} — ${difficultyFor(x.level)}`);if(x.videoTitle||x.title)l.push(`  Video: ${x.videoTitle||x.title}`);if(x.timestamp!=null)l.push(`  Timestamp: ${fmt(x.timestamp)}`);if(x.lastPosition!=null)l.push(`  Last position: ${fmt(x.lastPosition)}`);if(x.url)l.push(`  URL: ${x.url}`);if(x.createdAt||x.learnedAt)l.push(`  Saved: ${x.createdAt||x.learnedAt}`);if(x.pos)l.push(`  POS: ${x.pos}`);if(x.lemma)l.push(`  Lemma: ${x.lemma}`);if(x.tags?.length)l.push(`  Tags: ${x.tags.join(', ')}`);if(x.note)l.push(`  Notes: ${x.note}`);if(isSentenceItem(x)){l.push('  Complete sentence translation: '+(x.sentenceTranslation||x.translation||''));for(const w of (Array.isArray(x.words)&&x.words.length?x.words:deriveSentenceWords(x)))l.push(`    ${w.word} → ${w.translation||'—'} · ${w.posLabel||w.pos||'Other'} · lemma: ${w.lemma||'—'}${w.suffix?' · suffix: '+w.suffix:''}`)}l.push('')});return l.join('\n')}
function csv(items){let keys=[...new Set(items.flatMap(x=>Object.keys(x)))];return [keys.join(','),...items.map(x=>keys.map(k=>`"${String(Array.isArray(x[k])?x[k].join('|'):x[k]??'').replaceAll('"','""')}"`).join(','))].join('\n')}
function parseCSV(t){let lines=t.split(/\r?\n/).filter(Boolean);if(lines.length<2)return[];let h=split(lines[0]);return lines.slice(1).map(l=>{let v=split(l),x={};h.forEach((k,i)=>x[k]=v[i]||'');x.id=x.id||crypto.randomUUID();if(x.timestamp)x.timestamp=Number(x.timestamp);x.tags=String(x.tags||'').split('|').filter(Boolean);return x})}
function split(l){let a=[],c='',q=false;for(let i=0;i<l.length;i++){let x=l[i];if(x==='"'&&l[i+1]==='"'){c+='"';i++;continue}if(x==='"'){q=!q;continue}if(x===','&&!q){a.push(c);c='';continue}c+=x}a.push(c);return a}
function timecode(sec,type){let ms=Math.max(0,Math.round(Number(sec||0)*1000)),h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000),s=Math.floor(ms%60000/1000),z=ms%1000;return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}${type==='srt'?',':'.'}${String(z).padStart(3,'0')}`}
async function download(path,text,mime){let u=URL.createObjectURL(new Blob([text],{type:mime+';charset=utf-8'}));try{await chrome.downloads.download({url:u,filename:path,saveAs:false})}finally{setTimeout(()=>URL.revokeObjectURL(u),15000)}}
async function downloadBinary(path,bytes,mime){let blob=new Blob([bytes],{type:mime});let u=URL.createObjectURL(blob);try{await chrome.downloads.download({url:u,filename:path,saveAs:false})}finally{setTimeout(()=>URL.revokeObjectURL(u),15000)}}
async function pdfFromText(text){let lines=[];for(const raw of String(text).split(/\r?\n/)){let line=raw||' ';while(line.length>72){lines.push(line.slice(0,72));line=line.slice(72)}lines.push(line)}let pageHeight=1754,pageWidth=1240,margin=75,lineH=29,perPage=Math.floor((pageHeight-margin*2)/lineH),pagesData=[];for(let p=0;p<lines.length||!pagesData.length;p+=perPage){let chunk=lines.slice(p,p+perPage),canvas=document.createElement('canvas');canvas.width=pageWidth;canvas.height=pageHeight;let c=canvas.getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,pageWidth,pageHeight);c.fillStyle='#111';c.font='24px Arial, sans-serif';c.textBaseline='top';chunk.forEach((line,i)=>c.fillText(line,margin,margin+i*lineH));let b64=canvas.toDataURL('image/jpeg',0.9).split(',')[1];let bin=atob(b64),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);pagesData.push({bytes,width:pageWidth,height:pageHeight})}return buildImagePdf(pagesData)}
function buildImagePdf(pagesData){let objects=[];const add=s=>{objects.push(typeof s==='string'?new TextEncoder().encode(s):s);return objects.length};let catalogId=add('');let pagesId=add('');let pageIds=[],contentIds=[],imageIds=[];pagesData.forEach((pg,i)=>{pageIds.push(add(''));contentIds.push(add(''));imageIds.push(add(''))});let chunks=[],offsets=[0],pos=0;function obj(id,head,body){let h=new TextEncoder().encode(`${id} 0 obj\n${head}\nstream\n`),tail=new TextEncoder().encode('\nendstream\nendobj\n');let all=new Uint8Array(h.length+body.length+tail.length);all.set(h);all.set(body,h.length);all.set(tail,h.length+body.length);chunks.push(all);offsets[id]=pos;pos+=all.length}function plain(id,body){let b=new TextEncoder().encode(body);chunks.push(b);offsets[id]=pos;pos+=b.length}let total=objects.length; // object ids already reserved
pagesData.forEach((pg,i)=>{let content=new TextEncoder().encode(`q\n${pg.width} 0 0 ${pg.height} 0 0 cm\n/Im${i+1} Do\nQ\n`);let cHead=`<< /Length ${content.length} >>`;obj(contentIds[i],cHead,content);let iHead=`<< /Type /XObject /Subtype /Image /Width ${pg.width} /Height ${pg.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${pg.bytes.length} >>`;obj(imageIds[i],iHead,pg.bytes);let pHead=`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${pg.width} ${pg.height}] /Resources << /XObject << /Im${i+1} ${imageIds[i]} 0 R >> >> /Contents ${contentIds[i]} 0 R >>`;plain(pageIds[i],`${pageIds[i]} 0 obj\n${pHead}\nendobj\n`) });plain(pagesId,`${pagesId} 0 obj\n<< /Type /Pages /Count ${pageIds.length} /Kids [${pageIds.map(id=>id+' 0 R').join(' ')}] >>\nendobj\n`);plain(catalogId,`${catalogId} 0 obj\n<< /Type /Catalog /Pages ${pagesId} 0 R >>\nendobj\n`);let header=new TextEncoder().encode('%PDF-1.4\n%\xFF\xFF\xFF\xFF\n');let bodyParts=[header],cursor=header.length;let realOffsets={};for(const chunk of chunks){let m=new TextDecoder().decode(chunk).match(/^(\d+) 0 obj/);if(m)realOffsets[Number(m[1])]=cursor;bodyParts.push(chunk);cursor+=chunk.length}let xrefStart=cursor;let xref=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;for(let i=1;i<=objects.length;i++)xref+=String(realOffsets[i]||0).padStart(10,'0')+' 00000 n \n';xref+=`trailer\n<< /Size ${objects.length+1} /Root ${catalogId} 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;bodyParts.push(new TextEncoder().encode(xref));let totalLen=bodyParts.reduce((n,b)=>n+b.length,0),out=new Uint8Array(totalLen),at=0;for(const b of bodyParts){out.set(b,at);at+=b.length}return out}
'''
s=s[:start]+new3+s[end:]
# insert data-details-open handler before close
s=s.replace("if(e.target.matches('[data-close]'))e.target.closest('dialog')?.close();", "let doOpen=e.target.closest('[data-details-open]');if(doOpen){chrome.tabs.create({url:doOpen.dataset.detailsOpen});return}\n if(e.target.matches('[data-close]'))e.target.closest('dialog')?.close();")
p.write_text(s)
